[package]
name = "blitz-shell"
version = "0.0.0"
license.workspace = true
edition = "2021"

[features]
default = ["net", "accessibility", "menu", "tracing", "svg"]
svg = ["blitz-renderer-vello/svg"]
net = ["dep:tokio", "dep:reqwest", "dep:url", "dep:blitz-net"]
accessibility = ["dep:accesskit", "dep:accesskit_winit"]
menu = ["dep:muda"]
tracing = ["dep:tracing", "blitz-dom/tracing"]

[dependencies]
# Blitz dependencies
blitz-renderer-vello = { path = "../blitz-renderer-vello" }
blitz-dom = { path = "../blitz-dom", default-features = false }
blitz-html = { path = "../blitz-html" }
blitz-net = { path = "../blitz-net", optional = true }
blitz-traits = { path = "../blitz-traits" }

# Servo dependencies
style = { workspace = true }

# Windowing & Input
winit = { workspace = true }
muda = { workspace = true, default-features = false, features = ["serde"], optional = true }
accesskit = { workspace = true, optional = true }
accesskit_winit = {workspace = true, optional = true }

# IO & Networking
url = { workspace = true, features = ["serde"], optional = true }
tokio = { workspace = true, features = ["rt-multi-thread"], optional = true }
reqwest = { workspace = true, optional = true }

# Other dependencies
tracing = { workspace = true, optional = true }
futures-util = { workspace = true }

[target.'cfg(target_os = "android")'.dependencies]
android-activity = { version = "0.6.0", features = ["native-activity"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
