[package]
name = "blitz-dom"
version = "0.0.0"
license.workspace = true
edition = "2021"

[features]
default = ["tracing", "svg", "woff", "clipboard"]
tracing = ["dep:tracing"]
svg = ["dep:usvg"]
woff = ["dep:woff2"]
clipboard = ["dep:arboard"]

[dependencies]
# Blitz dependencies
blitz-traits = { path = "../blitz-traits" }
stylo_taffy = { path = "../stylo_taffy" }

# Servo dependencies
style = { workspace = true, features = ["servo"] }
selectors = { workspace = true }
style_config = { workspace = true }
style_traits = { workspace = true }
style_dom = { workspace = true }
app_units = { workspace = true }
euclid = { workspace = true, features = ["serde"] }
atomic_refcell = { workspace = true, features = ["serde"] }
string_cache = { workspace = true }
markup5ever = { workspace = true }

# DioxusLabs dependencies
taffy = { workspace = true }

# Linebender dependencies
parley = { workspace = true }
peniko = { workspace = true }
arboard = { workspace = true, optional = true }

# Other dependencies
slab = { workspace = true }
tracing = { workspace = true, optional = true }

# Media & Decoding
image = { workspace = true }
usvg = { workspace = true, optional = true }
woff2 = { workspace = true, optional = true }
html-escape = { workspace = true }

# IO & Networking
url = { workspace = true, features = ["serde"] }

# Input
winit = { workspace = true }

# Rendering
raw-window-handle = { workspace = true }
