[package]
name = "anyrender"
version = "0.0.0"
edition = "2021"
description = "An abstraction over rendering backends"
license.workspace = true

[dependencies]
kurbo = { workspace = true }
peniko = { workspace = true }
raw-window-handle = { workspace = true }